### ISSUE TITLE
SimpleVerticalAligner doesn't work with empty content

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-shell#107]
Having something like using `SimpleVerticalAligner.middle`:
```
builder.on(column(0)).addAligner(middle)
```
throws below error if cell content is empty.
```
java.lang.ArrayIndexOutOfBoundsException
    at java.lang.System.arraycopy(Native Method)
    at org.springframework.shell.table.SimpleVerticalAligner.align(SimpleVerticalAligner.java:81)
    at org.springframework.shell.table.Table.render(Table.java:136)
    at org.springframework.shell.table.Table.render(Table.java:51)
    at org.springframework.shell.core.AbstractShell.handleExecutionResult(AbstractShell.java:309)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:142)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
```
It works i.e. with `SimpleHorizontalAligner.center`.
```
builder.on(column(0)).addAligner(center)
```

**Comment by ericbottard** [comment]
Could you help me reproduce this with the most minimal testcase ?
I can't seem to get there. The following test case highlights a *different* exception being thrown:

```java
	@Test
	public void testNullCells() {
		TableModel model = new ArrayTableModel(new String[2][2]);
		Table table = new TableBuilder(model).on(CellMatchers.table()).addAligner(SimpleVerticalAligner.middle).build();
		String result = table.render(3);

	}
```

(with or without the Aligner, btw).

```
java.util.MissingFormatWidthException: %-0s

	at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:2954)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2725)
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2928)
```

**Comment by ericbottard** [comment]
OK, found it. This happens when some rows *have* content (hence given columns a width) and there are some `null`s in other rows.
