### ISSUE TITLE
Cannot validate multiple required Option

### ISSUE THREAD

**Issue by libe** [spring-projects/spring-shell#1150]
I am having trouble validating multiple required Option, here's my example:

```java
@Command(command = "dataset", group = "Dataset Commands")
class DatasetCommands {
    @Command(command = "describe", description = "Describe a dataset by id")
    String findById(@Option(required = true, description = "Project id") String projectId, 
                    @Option(required = true, description = "Dataset id") String datasetId)  {
        return String.format("Got projectId %s datasetId %s", projectId, datasetId);
    }
}
```

So I launch the command with
```
dataset describe 1
```

I get 

```
Got projectId 1 datasetId null
```

I would have expected to get something like "not all options are passed" exception but strange the command is **executed with the second option null**.

Any idea if I am doing something wrong?

Thanks in advance!

**Comment by maciekgaszynski** [comment]
I'm having issue even with single required option. Following docs https://docs.spring.io/spring-shell/reference/options/positional.html

```java
@Bean
  CommandRegistration commandRegistration() {
    return CommandRegistration.builder()
        .command("arity-strings-1")
        .withOption()
        .longNames("arg1")
        .required()
        .type(String[].class)
        .arity(0, 2)
        .and()
        .withTarget()
        .function(
            ctx -> {
              String[] arg1 = ctx.getOptionValue("arg1");
              return "Hello " + Arrays.asList(arg1);
            })
        .and()
        .build();
  }
```

Gives me:
```
shell:>arity-strings-1 one
java.lang.NullPointerException
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
```

and stacktrace gives
```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:220)
	at java.base/java.util.Arrays$ArrayList.<init>(Arrays.java:4199)
	at java.base/java.util.Arrays.asList(Arrays.java:4184)
```

Instead of expected:
```
shell:>arity-strings-1 one
Missing mandatory option --arg1.
```

**Comment by fmbenhassine** [comment]
This is fixed in v4. Here is a quick test with the [hello world sample](https://github.com/spring-projects/spring-shell/tree/main/spring-shell-samples/spring-shell-sample-hello-world), add the following command (adapted for v4) to the [main class](https://github.com/spring-projects/spring-shell/blob/main/spring-shell-samples/spring-shell-sample-hello-world/src/main/java/org/springframework/shell/samples/helloworld/SpringShellApplication.java):

```java
@Command(name = { "dataset", "describe" }, description = "Describe a dataset by id")
String findById(@Option(longName = "projectId", required = true, description = "Project id") String projectId,
		@Option(longName = "datasetId", required = true, description = "Dataset id") String datasetId) {
	return String.format("Got projectId %s datasetId %s", projectId, datasetId);
}
```

When I run the sample, it shows that all mandatory options are verified before execution:


```
$>dataset describe
Unable to run command dataset: Required option '--projectId' is missing.
$>dataset describe --projectId=1
Unable to run command dataset: Required option '--datasetId' is missing.
$>dataset describe --projectId=1 --datasetId=2
Got projectId 1 datasetId 2
```
