### ISSUE TITLE
Tab completion when using line continuation gives NPE

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-shell#174]
For the skipper command `search` which has a `--name` argument, hitting tab after the line continuation `\` gives a NPE

```
skipper:>search \
> --INFO : org.jline : Error while finding completion candidates
java.lang.StringIndexOutOfBoundsException: String index out of range: 3
	at java.lang.String.substring(String.java:1963)
	at org.springframework.shell.CompletionContext.upToCursor(CompletionContext.java:66)
	at org.springframework.shell.Shell.complete(Shell.java:221)
	at org.springframework.shell.jline.JLineShellAutoConfiguration$CompleterAdapter.complete(JLineShellAutoConfiguration.java:202)
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:3777)
	at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:3696)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:548)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:390)
	at org.springframework.shell.jline.DefaultShellApplicationRunner$JLineInputProvider.readInput(DefaultShellApplicationRunner.java:105)
	at org.springframework.shell.Shell.run(Shell.java:124)
	at org.springframework.shell.jline.DefaultShellApplicationRunner.run(DefaultShellApplicationRunner.java:80)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:767)
```
Instead of

```
skipper:>search --
--details   --name
```

**Comment by ericbottard** [comment]
Completion is not supported in continued lines (the hook is not even invoked by JLine).
But I'm not getting a NPE when pressing TAB on the newline, just a regular tab character.
I *do* get a NPE if I submit the command that way, but that is expected behavior given the command implementation I assume:
```
server-unknown:>search \
>
java.lang.NullPointerException
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
server-unknown:>stacktrace
java.lang.NullPointerException
	at org.springframework.cloud.skipper.shell.command.SkipperCommands.search(SkipperCommands.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

Your error above does not indicate a NPE btw, I'd be eager to know how to reproduce.

(I'm using the latest SNAPSHOT of Spring Shell btw)

**Comment by markpollack** [comment]
I prob got NPE and the exception above dong different things and made a mistake creating the issue.  I will revisit.  In any case, is there a way to make the experience better...I'm always tabbing - the above example was going to the extreme in that I did `-- <TAB>` with such a short command, but it came up in a more real world case when the command was getting long and I wanted to break things up.  Maybe in 'interactive' move you shouldn't even be able to do `\` since it really breaks common functionality.

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
