### ISSUE TITLE
Allow more than one @CliAvailabilityIndicator

### ISSUE THREAD

**Issue by daschl** [spring-projects/spring-shell#18]
Hi guys,

something is strange here. I have two classes that implement a CommandMarker (to group them by what they do).

Both get a object autowired that implements the state of the shell (like connected, disconnected and executes external commands).

Now here is the code in each of them:

``` java
    private static final String CONNECT = "cluster connect";

    private static final String DISCONNECT = "cluster disconnect";

    @CliAvailabilityIndicator({DISCONNECT})
    public boolean isConnected() {
        return shell.isConnected();
    }

    @CliAvailabilityIndicator({CONNECT})
    public boolean isDisconnected() {
        return !shell.isConnected();
    }
```

``` java
    private static final String GET = "bucket get";
    private static final String SET = "bucket set";
    private static final String ADD = "bucket add";
    private static final String REPLACE = "bucket replace";
    private static final String DELETE = "bucket delete";
    private static final String COUNT_DOCS = "bucket count-docs";

    @CliAvailabilityIndicator({GET, SET, ADD, REPLACE, DELETE, COUNT_DOCS})
    public boolean isConnected() {
        return shell.isConnected();
    }
```

The thing that both have in common is this:

``` java
    @Autowired
    private CouchbaseShell shell;
```

which is just a 

``` java
@Component
public class CouchbaseShell {
....
}
```

Now when I run it I get this exception

```
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shell': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Cannot specify an availability indicator for 'cluster disconnect' more than once
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1455)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:609)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:469)
    at org.springframework.shell.Bootstrap.<init>(Bootstrap.java:93)
    at org.springframework.shell.Bootstrap.<init>(Bootstrap.java:74)
    at org.springframework.shell.Bootstrap.main(Bootstrap.java:58)
Caused by: java.lang.IllegalArgumentException: Cannot specify an availability indicator for 'cluster disconnect' more than once
    at org.springframework.util.Assert.isTrue(Assert.java:65)
    at org.springframework.shell.core.SimpleParser.add(SimpleParser.java:1037)
    at org.springframework.shell.core.JLineShellComponent.afterPropertiesSet(JLineShellComponent.java:102)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1514)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452)
    ... 12 more
```

When I comment out the annotation with the method in one of the classes it works, but I'm not sure how they relate.. can someone clarify?

**Comment by ericbottard** [comment]
Closing this outdated Shell 1 issue. Spring Cloud Data Flow has examples of `@CliAvailabilityIndicator` + commands with spaces in them, so I'm assuming the error was somewhere else
