### ISSUE TITLE
Difference between spring-shell1 and LegacyParameterResolver 

### ISSUE THREAD

**Issue by arturbosch** [spring-projects/spring-shell#217]
When having a simple command with CliOption `""` and input `done bla bla`:
```
	@CliCommand(value = "done")
	public void finishCard(
			@CliOption(key = {"", "title"}, mandatory = true) String title) {
		System.out.println(title);
	}
```

the resolver crashes with following stacktrace:

```
kanbin>done bla bla
Anonymous option has already been set
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
kanbin>stacktrace
java.lang.IllegalArgumentException: Anonymous option has already been set
	at org.springframework.util.Assert.isTrue(Assert.java:92)
	at org.springframework.shell.legacy.LegacyParameterResolver.parseOptions(LegacyParameterResolver.java:239)
	at org.springframework.shell.legacy.LegacyParameterResolver.resolve(LegacyParameterResolver.java:85)
	at org.springframework.shell.Shell.resolveArgs(Shell.java:296)
	at org.springframework.shell.Shell.evaluate(Shell.java:167)
	at org.springframework.shell.Shell.run(Shell.java:134)
	at org.springframework.shell.jline.InteractiveShellApplicationRunner.run(InteractiveShellApplicationRunner.java:84)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:723)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:713)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at io.gitlab.arturbosch.tinbo.TinboKt.main(Tinbo.kt:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

In spring-shell1 the parameter title was successfully set to `bla bla`.
Is this a bug or planned behavior?

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
