### ISSUE TITLE
Dockerized spring-shell application

### ISSUE THREAD

**Issue by toudidel** [spring-projects/spring-shell#256]
I've received the following NullPointerException at org.springframework.shell.jline.ParsedLineInput.words(ParsedLineInput.java:44) when try to run docker container with spring-shell application:

`java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at pl.coderion.SpringShellApplication.main(SpringShellApplication.java:18) [classes!/:1.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [codegenerator.jar:1.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [codegenerator.jar:1.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [codegenerator.jar:1.0-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [codegenerator.jar:1.0-SNAPSHOT]
Caused by: java.lang.NullPointerException: null
	at org.springframework.shell.jline.ParsedLineInput.words(ParsedLineInput.java:44) ~[spring-shell-core-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
	at org.springframework.shell.Shell.noInput(Shell.java:214) ~[spring-shell-core-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
	at org.springframework.shell.Shell.evaluate(Shell.java:159) ~[spring-shell-core-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
	at org.springframework.shell.Shell.run(Shell.java:142) ~[spring-shell-core-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
	at org.springframework.shell.jline.InteractiveShellApplicationRunner.run(InteractiveShellApplicationRunner.java:84) ~[spring-shell-core-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	... 13 common frames omitted
`

Steps to reproduce the bug:

1. Generate app using Spring Initializr (https://start.spring.io/): Maven/Java/Spring Boot 2.1.3 with added only one dependency: Spring Shell.

2. Added Dockerfile to project:
`FROM openjdk:8-jdk-alpine`
`VOLUME /tmp`
`COPY target/project-1.0-SNAPSHOT.jar project.jar`
`ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/project.jar"]`

3. Build Docker image:
`docker build . -t project:latest`

4. Run the container:
`docker run project`

**Comment by cpinedo** [comment]
I had the same issue.

This solved my problem `https://stackoverflow.com/questions/51449432/spring-shell-appilication-inside-docker`

**Comment by C-Otto** [comment]
Clickable: https://stackoverflow.com/questions/51449432/spring-shell-appilication-inside-docker

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
