### ISSUE TITLE
Failed to execute ApplicationRunner in remote machine

### ISSUE THREAD

**Issue by shukiAnavi** [spring-projects/spring-shell#276]
Hi!

I've added the shell dependency to my spring-boot API server.
When I'm running the project locally, the 'shell>' option appears and I'm able to run the command that I defined. 
When I'm trying to start the service (run the jar) on my remote machine (Ubuntu) I'm getting this exception: 

> java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) ~[spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:778) ~[spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
	at com.sp.api.SpApiApplication.main(SpApiApplication.java:19) [classes!/:1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [sp-api-1.jar:1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [sp-api-1.jar:1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [sp-api-1.jar:1]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [sp-api-1.jar:1]
Caused by: java.lang.NullPointerException: null
	at org.springframework.shell.jline.ParsedLineInput.words(ParsedLineInput.java:44) ~[spring-shell-core-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.shell.Shell.noInput(Shell.java:194) ~[spring-shell-core-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.shell.Shell.evaluate(Shell.java:151) ~[spring-shell-core-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.shell.Shell.run(Shell.java:134) ~[spring-shell-core-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.shell.jline.InteractiveShellApplicationRunner.run(InteractiveShellApplicationRunner.java:84) ~[spring-shell-core-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:788) ~[spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]

The shell component:

> @ShellComponent
public class CustomShell {

	@Autowired
	private ImageManager imageManager;

	@ShellMethod(value = "save images")
	public String readAndSaveImages() {
		imageManager.saveImages();
		return "Done";
	}
}

The main spring-boot class:

> @SpringBootApplication
@EnableCaching
@EnableAsync
@EnableScheduling
public class SpApiApplication {

	public static void main(String[] args) {
		new SpringApplicationBuilder(SpApiApplication.class)
			.properties("spring.profiles.active")
			.build()
			.run(args);
	}
}

The dependencies are:

>  <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cache</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		 <dependency>
			<groupId>org.springframework.shell</groupId>
			<artifactId>spring-shell-starter</artifactId>
			<version>2.0.0.RELEASE</version>
		</dependency>

The spring-boot version: 2.0.2.RELEASE

Any ideas why this happens and how can I solve it?

**Comment by bjayach** [comment]
You can fix this by setting the spring shell to false before deploying to your remote server. Add the below to your spring application.properties file. set this to true when you want to run the program locally.
spring.shell.interactive.enabled=false

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
