### ISSUE TITLE
Boolean parameter's arity=1 is not working for lowercase boolean values(true/false)

### ISSUE THREAD

**Issue by rmunna** [spring-projects/spring-shell#305]
I have a shell method `write` with boolean option `overwrite`. I want to use the boolean filed to accept boolean value as the parameter instead of the flag. Fo that I created command like this.

```
@ShellMethod(key = "write", value = "write data to file")
 public String write(
         @ShellOption(value = "--overwrite", arity = 1   defaultValue = "true") Boolean overwrite) {

}
```

With boolean value in upper case , its working
`write --overwrite TRUE`

With boolean value in lower case , error is throwned.
`write --overwrite true`

stacktrace
```
org.springframework.shell.UnfinishedParameterResolutionException: Error trying to resolve '--overwrite [ true | false ]' using [--overwrite]
        at org.springframework.shell.standard.StandardParameterResolver.lambda$resolve$4(StandardParameterResolver.java:160)
        at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
        at org.springframework.shell.standard.StandardParameterResolver.resolve(StandardParameterResolver.java:138)
        at com.emc.ia.cli.config.uncustomized.ShellCustomizationConfig$IaParameterResolver.resolve(ShellCustomizationConfig.java:250)
        at org.springframework.shell.Shell.resolveArgs(Shell.java:316)
        at org.springframework.shell.Shell.evaluate(Shell.java:177)
        at org.springframework.shell.Shell.run(Shell.java:142)
        at org.springframework.shell.jline.InteractiveShellApplicationRunner.run(InteractiveShellApplicationRunner.java:84)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:775)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
```

**Comment by jvalkeal** [comment]
This is actually fixed in upcoming `2.1.0-M4`.
