### ISSUE TITLE
NoSuchBean exception during exception handling for ScriptShellApplicationRunner

### ISSUE THREAD

**Issue by imbirevkotlya** [spring-projects/spring-shell#308]
Steps to reproduce:

1. Use script runner, as described here: https://github.com/spring-projects/spring-shell/issues/307
2. Prepare some script file, where the exception should be thrown (for example, just throw an exception in your shellMethod)
2. Run the application with script file location passed as an argument (from point above), starts with '@'

You will see such behaviour:
`
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.shell.jline.InteractiveShellApplicationRunner' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.context.annotation.Lazy(value=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1695) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1253) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver$1.getTarget(ContextAnnotationAutowireCandidateResolver.java:90) ~[spring-context-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) ~[spring-aop-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.shell.jline.InteractiveShellApplicationRunner$$EnhancerBySpringCGLIB$$b06a1588.isEnabled(<generated>) ~[spring-shell-core-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.shell.result.ThrowableResultHandler.doHandleResult(ThrowableResultHandler.java:59) ~[spring-shell-core-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.shell.result.ThrowableResultHandler.doHandleResult(ThrowableResultHandler.java:38) ~[spring-shell-core-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.shell.result.TerminalAwareResultHandler.handleResult(TerminalAwareResultHandler.java:40) ~[spring-shell-core-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.shell.result.TypeHierarchyResultHandler.handleResult(TypeHierarchyResultHandler.java:50) ~[spring-shell-core-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.shell.Shell.run(Shell.java:144) ~[spring-shell-core-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.shell.jline.ScriptShellApplicationRunner.run(ScriptShellApplicationRunner.java:86) ~[spring-shell-core-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:775) [spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765) [spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
`

From my personal understanding, it happens because of such code in class ThrowableResultHandler:
`	
@Autowired
@Lazy
private InteractiveShellApplicationRunner interactiveRunner;

`

But the application in Script running mode just have no such interactiveRunner, so we just have such exception, described above

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
