### ISSUE TITLE
node-gyp on macos fails in e2e tests

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-shell#909]
At least macos11 env is now erroring:
```
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/runner/work/spring-shell/spring-shell/e2e/spring-shell-e2e/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "/Users/runner/work/spring-shell/spring-shell/e2e/spring-shell-e2e/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "/Users/runner/work/spring-shell/spring-shell/e2e/spring-shell-e2e/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
```

Looks like runners envs are upgrading to python 3.12 and that distutils were removed in that version.

**Comment by jvalkeal** [comment]
Looks to be from node, not directly from node-pty. There's starting to be issues in https://github.com/nodejs/node-gyp about distutils as people see these type of failures on gh actions.

**Comment by psaint-j** [comment]
Hello i have the same issue, how to you solve the probleme ?
