### ISSUE TITLE
Add Error Handling Infrastructure

### ISSUE THREAD

**Issue by ghillert** [spring-projects/spring-shell#99]
The truth is, shell command can fail. E.g. underlying REST services may return either **expected** or **unexpected** errors. **Currently, the output of errors cannot be customized in a decent manner**. 

This issue is possibly wrapper issue and may spawn sub-tickets for the following use-cases:

**Allow for the customization of errors using a central hook** 

This could be a common dedicated method that implements current behavior but that can be overridden by developers to fit their needs.

**Expected versus unexpected errors**

In many scenarios, Spring Shell commands may trigger exceptions that are expected (Such as a 404 returned by an underlying REST endpoint) or unexpected (Such as a 500 returned by an underlying REST endpoint).

For instance, an unexpected exception may trigger more console output (e.g. stack-traces) than expected exceptions.

It would be nice if there was a facility to specify Exception types that represent expected exceptions. 

**Remember Errors**

Users should also be able to introspect current and past errors. E.g:

1) Do not display a stacktrace when one occurs, but remember it
2) Add a `show last error` shell command, or something similar, to display the trace when one wants it

**Current situation**

Currently there are 2 places exceptions are printed to the console:

`org.springframework.shell.core.SimpleExecutionStrategy`

```
private Object invoke(ParseResult parseResult) {
    try {
        Method method = parseResult.getMethod();
        ReflectionUtils.makeAccessible(method);
        return ReflectionUtils.invokeMethod(method, parseResult.getInstance(), parseResult.getArguments());
    } catch (Throwable th) {
        logger.severe("Command failed " + th);
        return handleThrowable(th);
    }
}
```

Produces:

```
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Could not find stream definition named ticktock
```

And then in:

```
org.springframework.shell.core.AbstractShell
```

```
public CommandResult executeCommand(String line)

} catch (RuntimeException e) {
            setShellStatus(Status.EXECUTION_FAILED, line, parseResult);
            logger.log(Level.WARNING, e.getMessage(), e);
            // We rely on execution strategy to log it
            try {
                logCommandIfRequired(line, false);
            } catch (Exception ignored) {}
            return new CommandResult(false, null, e);
        }

```

Which produces:

```
org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Could not find stream definition named ticktock

    at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:52)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
    at org.springframework.web.client.RestTemplate.delete(RestTemplate.java:429)
    at org.springframework.cloud.dataflow.rest.client.StreamTemplate.destroy(StreamTemplate.java:107)
    at org.springframework.cloud.dataflow.shell.command.StreamCommands.destroyStream(StreamCommands.java:159)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
    at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:68)
    at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:59)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:130)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
    at java.lang.Thread.run(Thread.java:745)

```

See also: https://github.com/spring-cloud/spring-cloud-dataflow/issues/696

**Comment by ericbottard** [comment]
Tidying old 1.x issues.

Spring Shell 2 has support for displaying error details after the fact
